# Generated by Django 2.2.12 on 2022-06-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible_person', models.CharField(max_length=30, verbose_name='负责人')),
                ('content', models.TextField(default='空空如也', verbose_name='项目内容')),
                ('title', models.TextField(default='空空如也', verbose_name='项目标题')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '项目',
            },
        ),
    ]
