# Generated by Django 2.2.12 on 2022-06-25 03:27

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('front_researchGain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='content',
            field=tinymce.models.HTMLField(default='空空如也', verbose_name='项目内容'),
        ),
    ]
