# Generated by Django 2.2.12 on 2022-06-28 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_researchGain', '0002_auto_20220625_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': '项目'},
        ),
    ]
