# Generated by Django 2.2.12 on 2022-06-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_researchGain', '0003_auto_20220628_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='项目图片'),
            preserve_default=False,
        ),
    ]
