# Generated by Django 2.2.12 on 2022-06-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_resoure',
            name='publisher',
            field=models.CharField(default='空空如也', max_length=30, verbose_name='发布者'),
        ),
    ]
