# Generated by Django 2.2.12 on 2022-06-25 05:15

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('front_resource', '0002_book_resoure_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learn_Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(default='空空如也', max_length=30, verbose_name='发布者')),
                ('title', models.TextField(default='空空如也', verbose_name='资料标题')),
                ('content', tinymce.models.HTMLField(default='空空如也', verbose_name='资料内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '学习资料',
            },
        ),
    ]
