# Generated by Django 2.2.12 on 2022-06-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_resource', '0003_learn_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teach_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='视频标题')),
                ('video', models.FileField(upload_to='video')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
        ),
    ]
