# Generated by Django 2.2.12 on 2022-06-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_resource', '0005_auto_20220625_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teach_video',
            name='video',
            field=models.FileField(upload_to='front/video'),
        ),
    ]
