# Generated by Django 2.2.12 on 2022-06-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_resource', '0007_researcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='avatar',
            field=models.ImageField(default=1, upload_to='', verbose_name='专家头像'),
            preserve_default=False,
        ),
    ]
