# Generated by Django 2.2.12 on 2022-06-28 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_resource', '0008_researcher_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book_resoure',
            options={'verbose_name_plural': '文献资源'},
        ),
        migrations.AlterModelOptions(
            name='learn_resource',
            options={'verbose_name_plural': '学习资料'},
        ),
        migrations.AlterModelOptions(
            name='researcher',
            options={'verbose_name_plural': '研究人员'},
        ),
        migrations.AlterModelOptions(
            name='teach_video',
            options={'verbose_name_plural': '教学视频'},
        ),
    ]
