# Generated by Django 2.2.12 on 2022-06-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_resource', '0009_auto_20220628_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='teach_video',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='封面图片'),
            preserve_default=False,
        ),
    ]
