# Generated by Django 2.2.12 on 2022-06-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_resource', '0010_teach_video_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher_source',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='专家名字')),
                ('content', models.TextField(verbose_name='资源')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name_plural': '专家资源',
            },
        ),
    ]
