# Generated by Django 2.2.12 on 2022-06-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_resource', '0011_researcher_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher_source',
            name='title',
            field=models.TextField(default=1, verbose_name='论文标题'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='researcher_source',
            name='content',
            field=models.TextField(verbose_name='论文内容'),
        ),
    ]
