# Generated by Django 2.2.12 on 2022-06-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20220614_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(null=True),
        ),
    ]
