# Generated by Django 2.2.12 on 2022-06-16 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_auto_20220615_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.TextField(verbose_name='话题标题')),
                ('topic_content', models.TextField(null=True, verbose_name='话题内容')),
                ('topic_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('comment_number', models.IntegerField(default=0, verbose_name='评论数量')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='评论发布时间')),
                ('comment_content', models.TextField(verbose_name='评论内容')),
                ('parent_comment_ID', models.IntegerField(null=True)),
                ('topicID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.Topic')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.User')),
            ],
        ),
    ]
