# Generated by Django 2.2.12 on 2022-06-17 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_comments_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('-create_time',), 'verbose_name': '话题管理'},
        ),
        migrations.AddField(
            model_name='topic',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='topic',
            name='sumary',
            field=models.TextField(default='空空如也', verbose_name='摘要信息'),
        ),
        migrations.AddField(
            model_name='topic',
            name='total_views',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.AddField(
            model_name='topic',
            name='updated_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间'),
        ),
    ]
