# Generated by Django 2.2.12 on 2022-06-20 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_auto_20220618_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='userID',
            new_name='username',
        ),
    ]
