# Generated by Django 2.2.12 on 2022-06-20 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_auto_20220620_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='username',
            new_name='userID',
        ),
    ]
