# Generated by Django 2.2.12 on 2022-06-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_auto_20220620_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='publisher',
            field=models.CharField(default='空空如也', max_length=30, verbose_name='评论发布者'),
        ),
    ]
