# Generated by Django 2.2.12 on 2022-06-24 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0013_comments_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': '评论管理'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户管理'},
        ),
    ]
