# Generated by Django 2.2.12 on 2022-06-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_news', '0002_auto_20220624_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': '新闻管理'},
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='首页图片'),
            preserve_default=False,
        ),
    ]
