# Generated by Django 2.2.12 on 2022-06-28 06:37

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('front_news', '0003_auto_20220628_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='首页图片')),
                ('title', models.TextField(default='空空如也', verbose_name='工作标题')),
                ('content', tinymce.models.HTMLField(default='空空如也', verbose_name='工作内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '工作动态',
            },
        ),
    ]
